name: CI

on: [push]

jobs:  
  build:
    strategy:
      matrix:
        agent: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ] 
    runs-on: ${{ matrix.agent }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    - uses: actions/checkout@v1
    - name: configure
      run: mkdir build && cd build && cmake ./..
    - name: build
      run: cmake --build build